import jsPDF from "jspdf";

const SECTIONS = [
  { key: "subjective",  label: "S — Subjective",  color: "#EFF6FF" },
  { key: "objective",   label: "O — Objective",   color: "#F0FDF4" },
  { key: "assessment",  label: "A — Assessment",  color: "#FFFBEB" },
  { key: "plan",        label: "P — Plan",        color: "#FDF4FF" },
];

export default function SOAPNote({ note, patientId }) {

  const copyNote = () => {
    const text = SECTIONS.map(s => `${s.label}\n${note[s.key]}`).join("\n\n");
    navigator.clipboard.writeText(text);
    alert("Note copied to clipboard!");
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(15, 76, 129);
    doc.rect(0, 0, pageWidth, 25, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("ClinicalAI — SOAP Clinical Note", 14, 16);

    // Meta info
    doc.setFillColor(240, 244, 248);
    doc.rect(0, 25, pageWidth, 18, "F");
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Patient ID: ${patientId || "Unknown"}`, 14, 34);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 40);
    doc.text("AI-generated note — Doctor must review before adding to patient records", pageWidth - 14, 34, { align: "right" });

    let y = 52;

    // SOAP sections
    const sectionColors = {
      subjective:  [239, 246, 255],
      objective:   [240, 253, 244],
      assessment:  [255, 251, 235],
      plan:        [253, 244, 255],
    };

    SECTIONS.forEach(({ key, label }) => {
      const content = note[key] || "Not documented";
      const lines = doc.splitTextToSize(content, pageWidth - 28);
      const boxHeight = lines.length * 6 + 16;

      // Check if we need a new page
      if (y + boxHeight > 270) {
        doc.addPage();
        y = 20;
      }

      // Section background
      const [r, g, b] = sectionColors[key];
      doc.setFillColor(r, g, b);
      doc.roundedRect(12, y, pageWidth - 24, boxHeight, 3, 3, "F");

      // Section border
      doc.setDrawColor(200, 210, 220);
      doc.roundedRect(12, y, pageWidth - 24, boxHeight, 3, 3, "S");

      // Section label
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(label.toUpperCase(), 18, y + 8);

      // Section content
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(lines, 18, y + 16);

      y += boxHeight + 8;
    });

    // Footer
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 280, pageWidth, 17, "F");
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by ClinicalAI — Multilingual Patient Assistant", 14, 289);
    doc.text("Free · Open Source · For Small Clinics", pageWidth - 14, 289, { align: "right" });

    // Save
    doc.save(`SOAP_Note_${patientId || "patient"}_${new Date().toISOString().split("T")[0]}.pdf`);
  };

  return (
    <div>
      <div style={{
        display: "flex", justifyContent: "space-between",
        alignItems: "center", marginBottom: "12px"
      }}>
        <span style={{ fontWeight: "700", fontSize: "14px", color: "#0F172A" }}>
          Generated SOAP Note
        </span>
        <div style={{ display: "flex", gap: "8px" }}>
          <button onClick={copyNote} style={{
            padding: "6px 12px", background: "#F1F5F9",
            border: "none", borderRadius: "8px",
            cursor: "pointer", fontSize: "12px", fontWeight: "600", color: "#475569"
          }}>
            Copy Note
          </button>
          <button onClick={downloadPDF} style={{
            padding: "6px 14px", background: "#0F4C81",
            border: "none", borderRadius: "8px",
            cursor: "pointer", fontSize: "12px",
            fontWeight: "600", color: "white",
            display: "flex", alignItems: "center", gap: "6px"
          }}>
            Download PDF
          </button>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
        {SECTIONS.map(({ key, label, color }) => (
          <div key={key} style={{
            background: color, borderRadius: "10px", padding: "12px"
          }}>
            <div style={{
              fontSize: "10px", fontWeight: "700",
              color: "#64748B", marginBottom: "6px", letterSpacing: "0.06em"
            }}>
              {label}
            </div>
            <div style={{
              fontSize: "13px", color: "#1E293B", lineHeight: "1.7"
            }}>
              {note[key] || "Not documented"}
            </div>
          </div>
        ))}
      </div>

      <div style={{
        background: "#FFF7ED", border: "1px solid #FED7AA",
        borderRadius: "8px", padding: "10px 14px", marginTop: "12px",
        fontSize: "12px", color: "#9A3412"
      }}>
        AI-generated note. Doctor must review before adding to patient records.
      </div>
    </div>
  );
}